api_platform:
    keep_legacy_inflector: false
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        json: ['application/json']
    graphql:
        graphql_playground:
            enabled: false
    title: Hello API Platform
    version: 1.0.0

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
