api_platform:
    title: ToBikeToGo API
    version: 1.0.0
    description: API for ToBikeToGo
    collection:
        pagination:
            enabled: true
            enabled_parameter_name: 'pagination'
            items_per_page_parameter_name: 'itemsPerPage'
            page_parameter_name: 'page'
            partial_parameter_name: 'partial'
    keep_legacy_inflector: false
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        json: ['application/json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    # eager_loading:
    #     enabled: true
    #     max_joins: 1000
    graphql:
        graphql_playground:
            enabled: false

    defaults:
        pagination_enabled: true # Enable pagination globally
        pagination_items_per_page: 30 # Number of elements per page
        pagination_partial: true # Disable page count

        pagination_client_enabled: true # Allow client to enable pagination
        pagination_client_items_per_page: true # Allow client to change limit
        pagination_client_partial: true # Allow client to disable page count
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header