vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
       media_upload:
           uri_prefix: /uploads/media
           upload_destination: '%kernel.project_dir%/public/uploads/media'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
