name: Test Back

on:
    push:
        branches:
            - main
        paths:
            - 'api/**'
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    sonarqube:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  sparse-checkout: |
                    .github
                    api
                    vendor
                    phpstan.dist.neon
                  fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
                    
            - name: Install dependencies
              run: |
                cd api/
                composer install --prefer-dist --no-progress --no-interaction
                mkdir -p test-reports
                mkdir -p tests
                composer run-script phpstan

            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              with: 
                projectBaseDir: ./api
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
