name: Reset and update database

concurrency:
  group: production
  cancel-in-progress: true

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        # Backup the database
        backup:
            description: 'Backup and restore the database'
            type: choice
            required: false
            default: 'no'
            options:
                - 'restore and backup'
                - 'backup'
                - 'restore'
                - 'no'
        # load fixtures
        load_fixtures:
            description: 'Load fixtures'
            type: boolean
            required: false
            default: false

jobs:
    reset:
        name: Reset and update database
        runs-on: ubuntu-latest
        steps:
            - name: Backup database
              if: ${{ github.event.inputs.backup == 'backup' || github.event.inputs.backup == 'restore and backup' }}
              uses: garygrossgarten/github-action-ssh@release
              with:
                command: |
                    export PGUSER=${{ secrets.PGUSER }}
                    export PGPASSWORD=${{ secrets.PGPASSWORD }}
                    cd /home/debian/ToBikeToGo/api/
                    php bin/console doctrine:database:backup
                host: ${{ secrets.HOST }}
                username: ${{ secrets.username }}
                password: ${{ secrets.PASSPHRASE }}

            - name: Reset database
              uses: garygrossgarten/github-action-ssh@release
              with:
                command: |
                    cd /home/debian/ToBikeToGo/api/
                    php bin/console doctrine:database:drop --force
                    php bin/console doctrine:database:create
                    php bin/console doctrine:migrations:migrate --no-interaction
                    curl --verbose https://api.tobiketogo.shop/api
                    curl --verbose https://tobiketogo.shop
                    curl -o /dev/null -s -w "%{http_code}\n" https://api.tobiketogo.shop/api
                    curl -o /dev/null -s -w "%{http_code}\n" https://tobiketogo.shop
                host: ${{ secrets.HOST }}
                username: ${{ secrets.username }}
                password: ${{ secrets.PASSPHRASE }}
        
            - name: Load fixtures
              if: ${{ github.event.inputs.load_fixtures == 'true' }}
              uses: garygrossgarten/github-action-ssh@release
              with:
                command: |
                    cd /home/debian/ToBikeToGo/api/
                    php bin/console doctrine:fixtures:load --no-interaction
                host: ${{ secrets.HOST }}
                username: ${{ secrets.username }}
                password: ${{ secrets.PASSPHRASE }}

            - name: Restore database
              if: ${{ github.event.inputs.backup == 'restore' || github.event.inputs.backup == 'restore and backup' }}
              uses: garygrossgarten/github-action-ssh@release
              with:
                command: |
                    export PGUSER=${{ secrets.PGUSER }}
                    export PGPASSWORD=${{ secrets.PGPASSWORD }}
                    cd /home/debian/ToBikeToGo/api/
                    php bin/console doctrine:database:restore
                host: ${{ secrets.HOST }}
                username: ${{ secrets.username }}
                password: ${{ secrets.PASSPHRASE }}
              