name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    name: Connexion au serveur de prod
    runs-on: ubuntu-latest
    steps:
    - name: Connect with SSH to server and deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          cd /home/debian/ToBikeToGo/
          git stash
          git pull --rebase origin main
          git log --oneline -n 5
          git stash pop
          cd api/
          composer install --no-dev --optimize-autoloader
          APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
          cd ../front
          yarn install
          yarn build --mode production
          curl --verbose https://api.tobiketogo.shop/api
          curl --verbose https://tobiketogo.shop
          curl -o /dev/null -s -w "%{http_code}\n" https://api.tobiketogo.shop/api
          curl -o /dev/null -s -w "%{http_code}\n" https://tobiketogo.shop
        host: ${{ secrets.HOST }}
        username: ${{ secrets.username }}
        password: ${{ secrets.PASSPHRASE }}
